#!/usr/bin/env python2

import sys
from py_uav_path_planning import LocalPathPlanner

if __name__ == '__main__':
    if False:  # len(sys.argv) != 2:
        print("obstacle_sensor node not started. " +
              "Usage is: rosrun uav_path_planning obstacle_sensor_node goal_coordinate")
    else:
        node = LocalPathPlanner()
        node.start([10, 0, 0.5])  # sys.argv[1])
